name: picpay-simplified-api

services:
  rdbms:
    container_name: picpay-simplified-rdbms
    image: bitnami/postgresql:16
    restart: always
    env_file:
      - .env.docker
    ports:
      - 5432:5432
    volumes:
      - picpay-simplified-rdbms-data:/bitnami/postgresql

volumes:
  picpay-simplified-rdbms-data:
